import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";

const baskerville = localFont({
    src: [
        {
            path: './fonts/Baskerville.ttf',
            weight: '400',
            style: 'normal',
        },
        {
            path: './fonts/Baskerville-Medium.otf',
            weight: '500',
            style: 'medium',
        },
        {
            path: './fonts/Baskerville-Semibold.ttf',
            weight: '600',
            style: 'semibold',
        },
    ],
    variable: '--font-baskerville',
    display: 'swap',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${baskerville.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}
